// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7EsMjkos0vV0MVKZRoK0vPDpbr9KNDwo',
    appId: '1:578014482395:web:0258e0581c5cf1fc13e1fe',
    messagingSenderId: '578014482395',
    projectId: 'chat-app-e8033',
    authDomain: 'chat-app-e8033.firebaseapp.com',
    storageBucket: 'chat-app-e8033.appspot.com',
    measurementId: 'G-1JFWG12TGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3d2j97baCDsWXRZmBs93LJ6osB-147qM',
    appId: '1:578014482395:android:ceb3a611de1e40eb13e1fe',
    messagingSenderId: '578014482395',
    projectId: 'chat-app-e8033',
    storageBucket: 'chat-app-e8033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8jAglCYRl80M87mEl9bN6hjFjSEfkKjo',
    appId: '1:578014482395:ios:34fd90b655ff9c8813e1fe',
    messagingSenderId: '578014482395',
    projectId: 'chat-app-e8033',
    storageBucket: 'chat-app-e8033.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8jAglCYRl80M87mEl9bN6hjFjSEfkKjo',
    appId: '1:578014482395:ios:34fd90b655ff9c8813e1fe',
    messagingSenderId: '578014482395',
    projectId: 'chat-app-e8033',
    storageBucket: 'chat-app-e8033.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7EsMjkos0vV0MVKZRoK0vPDpbr9KNDwo',
    appId: '1:578014482395:web:5e003236eca8c2eb13e1fe',
    messagingSenderId: '578014482395',
    projectId: 'chat-app-e8033',
    authDomain: 'chat-app-e8033.firebaseapp.com',
    storageBucket: 'chat-app-e8033.appspot.com',
    measurementId: 'G-7RSKRFP3PK',
  );
}
